name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: publish
      run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN}} --verbose 
